name: 'bloodhound'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  bloodhound:
    staging:
      +materialized: view
      +schema: staging
