---
config:
  theme: mc
  layout: dagre
  look: neo
---
flowchart BT
 subgraph loader["Loading"]
        SourceFS["@dlt.source<br>FileSystem"]
        FSRes["@dlt.resource<br>filtered_files"]
    
        SourceFS -- return --> FSRes
  end
 subgraph sources["Resources"]
        loader
        Kube["@dlt.source<br/>KubernetesGraph"]
        AWS["@dlt.source<br/>AWSGraph"]

        KubeRes["@dlt.transformer<br/>RoleBinding"]
        AWSRes["@dlt.transformer<br/>Role"]

        Kube -- returns --> KubeRes
        FSRes -- yield result --> Kube

        AWS -- returns --> AWSRes
        FSRes -- yield result --> AWS

        

  end
 subgraph parsing["Parsing"]
        sources
        RoleBindingNode["RoleBindingNode Model"]
        RoleNode["RoleNode Model"]

        KubeRes -- yield result --> RoleBindingNode
        AWSRes -- yield result --> RoleNode

  end
 subgraph destination["Finalize"]
        parsing
        FileOut["@dlt.destination<br>opengraph_file"]
        ApiOut["@dlt.destination<br>opengraph_api"]
        File["{resource-name}-{batch_no}.json"]
        API["https://localhost:8080/api"]
        Choice{"destination"}

        RoleBindingNode --> Choice
        RoleNode --> Choice
        Choice -- file --> FileOut
        Choice -- api --> ApiOut
        FileOut -- write --> File
        ApiOut -- post --> API

        end
    
    
    
