KUBE_ICONS = {
    "KubeCluster": "globe",
    "KubeNode": "server",
    "KubePod": "cube",
    "KubeReplicaSet": "cubes",
    "KubeDeployment": "cubes",
    "KubeStatefulSet": "cubes",
    "KubeDaemonSet": "cubes",
    "KubeNamespace": "folder",
    "KubeRole": "id-badge",
    "KubeRoleBinding": "link",
    "KubeClusterRole": "id-badge",
    "KubeClusterRoleBinding": "link",
    "KubeScopedRole": "id-badge",
    "KubeScopedRoleBinding": "link",
    "KubeServiceAccount": "user-cog",
    "KubeUser": "user",
    "AWSIAMUser": "user",
    "KubeGroup": "user-group",
    "KubeResource": "gear",
    "KubeResourceGroup": "gears",
    "KubeSecret": "key",
    "KubeVolume": "folder",
}
