KUBE_ICONS = {
    "K8sCluster": "globe",
    "K8sNode": "server",
    "K8sPod": "cube",
    "K8sReplicaSet": "cubes",
    "K8sDeployment": "cubes",
    "K8sStatefulSet": "cubes",
    "K8sDaemonSet": "cubes",
    "K8sNamespace": "folder",
    "K8sRole": "id-badge",
    "K8sRoleBinding": "link",
    "K8sClusterRole": "id-badge",
    "K8sClusterRoleBinding": "link",
    "K8sScopedRole": "id-badge",
    "K8sScopedRoleBinding": "link",
    "K8sServiceAccount": "user-cog",
    "K8sUser": "user",
    "AWSIAMUser": "user",
    "K8sGroup": "user-group",
    "K8sResource": "gear",
    "K8sResourceGroup": "gears",
    "K8sSecret": "key",
    "K8sVolume": "folder",
}
